Repository precog/quasar, pull requests merged in 2018-11, with the labels that each got.

#3922 Revert "82.0.7: No more Normalizable"
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Coalesce.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
  qscript/src/main/scala/quasar/qscript/rewrites/ShiftRead.scala
  qscript/src/main/scala/quasar/qscript/rewrites/SimplifyJoin.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
  qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
  qsu/src/main/scala/quasar/qsu/MinimizeAutoJoins.scala
  qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala
Labels: version: revision

#3924 s/rewritePushdown/optimize/
  connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
Labels: version: revision

#3923 Change evalPivot to evalSinglePivot in ParseInstructionSpec
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
  mimir/src/main/scala/quasar/mimir/RValueParseInstructionInterpreter.scala
  mimir/src/test/scala/quasar/mimir/evaluate/RValueParseInstructionSpec.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/SinglePivotPlate.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/table/TectonicParseInstructionSpec.scala
Labels: version: revision

#3925 Reduce the size of generated Dimensions in tests.
  qscript/src/test/scala/quasar/qscript/provenance/DimensionsGenerator.scala
Labels: version: revision

#3926 Add support for creating Disposable from a cats.effect.Resource
  foundation/src/main/scala/quasar/Disposable.scala
Labels: version: feature

#3927 Only dispose when subsequent acquisition fails
  foundation/src/main/scala/quasar/Disposable.scala
  foundation/src/test/scala/quasar/DisposableSpec.scala
Labels: version: revision

#3928 Singleton ds should list resource as a resource
  connector/src/main/scala/quasar/connector/datasource/SingletonDatasource.scala
  connector/src/test/scala/quasar/connector/datasource/SingletonDatasourceSpec.scala
Labels: version: revision

#3931 Remove out-of-date info from the README
  README.md
Labels: version: revision

#3938 Add phase result for qscript rewrite phase
  connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
  it/src/test/scala/quasar/regression/RegressionQScriptEvaluator.scala
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
Labels: version: revision

#3945 Delete ExpandDirs and DiscoverPath
  build.sbt
  connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
  impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
  impl/src/main/scala/quasar/impl/evaluate/FederatingQueryEvaluator.scala
  impl/src/test/scala/quasar/impl/evaluate/FederatingQueryEvaluatorSpec.scala
  it/src/test/scala/quasar/regression/RegressionQScriptEvaluator.scala
  mimir/src/main/scala/quasar/mimir/evaluate/FederatedShiftedReadPlanner.scala
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
  qscript/src/main/scala/quasar/qscript/DiscoverPath.scala
  qscript/src/main/scala/quasar/qscript/InterpretedRead.scala
  qscript/src/main/scala/quasar/qscript/Read.scala
  qscript/src/main/scala/quasar/qscript/ShiftedRead.scala
  qscript/src/main/scala/quasar/qscript/package.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Coalesce.scala
  qscript/src/main/scala/quasar/qscript/rewrites/ExpandDirs.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
  qscript/src/main/scala/quasar/qscript/rewrites/ShiftReadDir.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
  qscript/src/test/scala/quasar/qscript/QScriptHelpers.scala
  qscript/src/test/scala/quasar/qscript/rewrites/RewritePushdownSpec.scala
  qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
  qscript/src/test/scala/quasar/qscript/rewrites/ShiftReadSpec.scala
  qsu/src/main/scala/quasar/qsu/Graduate.scala
  qsu/src/test/scala/quasar/qsu/GraduateSpec.scala
  qsu/src/test/scala/quasar/qsu/LPtoQSSpec.scala
Labels: version: breaking

#3946 Added autobump for azure
  scripts/quasarPublishAndTag
Labels: version: revision

#3952 Add woodstox as a dep as a quick and dirty way to get azure working
  project/Dependencies.scala
Labels: version: revision

#3953 Added UTF-8 byte-order mark to output streams from the REPL
  foundation/src/main/scala/quasar/contrib/fs2/pipe.scala
  repl/src/main/scala/quasar/repl/Evaluator.scala
Labels: version: feature

#3955 Added autobump for slamdata/quasar-datasource-url
  scripts/quasarPublishAndTag
Labels: version: revision

#3961 Delete a couple unused functions
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
  qscript/src/main/scala/quasar/qscript/rewrites/SimplifyJoin.scala
Labels: version: revision

#3965 Mark test as flaky
  impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
Labels: version: revision

#3970 Use QScriptEducated in place of duplicate QScriptRead
  impl/src/main/scala/quasar/impl/evaluate/FederatedQuery.scala
  impl/src/test/scala/quasar/impl/evaluate/FederatingQueryEvaluatorSpec.scala
  mimir/src/main/scala/quasar/mimir/evaluate/FederatedReadPlanner.scala
  qscript/src/main/scala/quasar/qscript/package.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
  qsu/src/test/scala/quasar/qsu/GraduateSpec.scala
  qsu/src/test/scala/quasar/qsu/LPtoQSSpec.scala
Labels: version: breaking

#3969 Gracefully handle a missing plugins dir
  impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
Labels: version: revision

#3972 Clean up the types in qscript rewrites
  connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
  it/src/test/scala/quasar/regression/RegressionQScriptEvaluator.scala
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
  qscript/src/main/scala/quasar/qscript/TTypes.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
  qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
  qsu/src/main/scala/quasar/qsu/QSUTTypes.scala
Labels: version: revision

#3973 Delete theta join filter rewrite
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
  qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
Labels: version: revision

#3975 Delete DedupeGuards and ExtractFiltering
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
  qscript/src/main/scala/quasar/qscript/rewrites/DedupeGuards.scala
  qscript/src/main/scala/quasar/qscript/rewrites/ExtractFiltering.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
  qscript/src/test/scala/quasar/qscript/MapFuncCoreSpec.scala
  qscript/src/test/scala/quasar/qscript/rewrites/ExtractFilteringSpec.scala
Labels: version: revision

#3978 Move freeMF to MapFuncCore
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
  qsu/src/main/scala/quasar/qsu/MinimizeAutoJoins.scala
  qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala
Labels: version: revision

#3980 Added mongo to quasar autobump
  scripts/quasarPublishAndTag
Labels: version: revision
