Repository precog/quasar, pull requests merged in 2018-09, with the labels that each got.

#3780 Specs related upgrades
  frontend/src/main/scala/quasar/frontend/logicalplan/Optimizer.scala
  project/Dependencies.scala
Labels: version: revision

#3776 Introduce MalformedResource to ResourceError
  connector/src/main/scala/quasar/connector/ResourceError.scala
Labels: version: breaking

#3785 fix round for doubles
  frontend/src/test/scala/quasar/std/StdLibSpec.scala
  mimir/src/main/scala/quasar/mimir/MathLib.scala
  mimir/src/main/scala/quasar/mimir/UnaryLib.scala
  mimir/src/test/scala/quasar/mimir/MathLibSpecs.scala
  mimir/src/test/scala/quasar/mimir/StringLibSpecs.scala
Labels: version: revision

#3787 Refactor regression test runner to use portable file paths
  it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala
Labels: version: revision

#3790 upgrade scalaz to 7.2.26
  project/Dependencies.scala
Labels: version: revision

#3789 OffsetDateTime toEpochSeconds returns seconds, not milliseconds
  impl/src/main/scala/quasar/impl/table/PreparationsManager.scala
  impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala
Labels: version: revision

#3791 fix to_timestamp for integer values which are not a Long
  frontend/src/test/scala/quasar/std/StdLibSpec.scala
  mimir/src/main/scala/quasar/mimir/TimeLib.scala
Labels: version: revision

#3793 Upgrade qdata to 2.0.0
  blueeyes/src/main/scala/quasar/precog/common/CValue.scala
  blueeyes/src/main/scala/quasar/precog/common/QDataRValue.scala
  blueeyes/src/test/scala/quasar/precog/common/QDataRValueSpec.scala
  common/src/main/scala/quasar/common/data/Data.scala
  common/src/main/scala/quasar/common/data/QDataData.scala
  common/src/test/scala/quasar/common/data/QDataDataSpec.scala
  qdata-version
Labels: version: revision

#3795 parameterize consumption mode in benchmarks
  yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/FromRValuesBenchmark.scala
  yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/LeftShiftBenchmark.scala
  yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/SliceTools.scala
Labels: version: revision

#3796 Updated sbt-slamdata
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#3799 Remove `$obj` from precise json.
  README.md
  frontend/src/main/scala/quasar/frontend/data/DataCodec.scala
  frontend/src/test/scala/quasar/frontend/data/DataCodecSpec.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Labels: version: breaking

#3801 add signal to track whether write in MimirPTableStore has completed
  mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala
Labels: version: revision

#3803 add signal to track whether write in MimirPTableStore has completed (with closing fix)
  mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala
  niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala
Labels: version: revision

#3804 Allow limiting the amount of time spent computing a resource schema
  api/src/main/scala/quasar/api/datasource/Datasources.scala
  api/src/test/scala/quasar/api/datasource/DatasourcesSpec.scala
  api/src/test/scala/quasar/api/datasource/MockDatasources.scala
  impl/src/main/scala/quasar/impl/datasources/DatasourceControl.scala
  impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
  impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
  impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
  impl/src/test/scala/quasar/impl/datasources/MockDatasourceControl.scala
  repl/src/main/scala/quasar/repl/Evaluator.scala
Labels: version: breaking

#3805 More robust test of schema halting after time limit.
  impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
Labels: version: revision

#3807 Add lenses for SstEvalConfig
  impl/src/main/scala/quasar/impl/schema/SstEvalConfig.scala
Labels: version: revision

#3808 Upgrade qdata-version to 2.1.0
  common/src/main/scala/quasar/common/data/PreciseKeys.scala
  frontend/src/main/scala/quasar/frontend/data/DataCodec.scala
  frontend/src/test/scala/quasar/frontend/data/DataCodecSpec.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalDatasource.scala
  impl/src/main/scala/quasar/impl/parse/QDataFacade.scala
  impl/src/main/scala/quasar/impl/parse/QDataPreciseFacade.scala
  impl/src/test/scala/quasar/impl/parse/QDataFacadeSpec.scala
  impl/src/test/scala/quasar/impl/parse/QDataPreciseFacadeSpec.scala
  project/Dependencies.scala
  qdata-version
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Labels: version: feature

#3812 Disable publishing documentation artifact.
  .travis.yml
  build.sbt
Labels: version: revision

#3814 Adds an optimize qscript rewrite stage
  connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Optimize.scala
  qscript/src/test/scala/quasar/qscript/rewrites/OptimizeSpec.scala
Labels: version: revision

#3817 Remove a bunch of Injectable[G, QScriptTotal] requirements
  qscript/src/main/scala/quasar/qscript/package.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
Labels: version: revision

#3819 Correct Equal[ShiftedRead[A]]
  qscript/src/main/scala/quasar/qscript/Read.scala
  qscript/src/main/scala/quasar/qscript/ShiftedRead.scala
  qscript/src/test/scala/quasar/qscript/rewrites/ShiftReadSpec.scala
Labels: version: revision

#3823 Added an integration test for ch2113
  it/src/main/resources/tests/real-giraffe.data
  it/src/main/resources/tests/shiftRealGiraffe.test
Labels: version: revision

#3824 Lifted filter autojoin restrictions a bit
  qsu/src/main/scala/quasar/qsu/minimizers/FilterToCond.scala
  qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Labels: version: revision

#3831 Delete DeepShape and ShapePreserving qscript analyses
  qscript/src/main/scala/quasar/qscript/analysis/DeepShape.scala
  qscript/src/main/scala/quasar/qscript/analysis/ShapePreserving.scala
  qscript/src/test/scala/quasar/qscript/analysis/DeepShapeSpec.scala
  qscript/src/test/scala/quasar/qscript/analysis/ShapePreservingSpec.scala
Labels: version: revision

#3834 Add integration tests for top-level shifting
  it/src/main/resources/tests/real-giraffe-plus.data
  it/src/main/resources/tests/shiftGiraffeExcludeId.test
  it/src/main/resources/tests/shiftGiraffeIdOnly.test
  it/src/main/resources/tests/shiftGiraffeIncludeId.test
  it/src/main/resources/tests/shiftGiraffeIncludeIdAndField.test
Labels: version: revision
