Repository precog/quasar, pull requests merged in 2018-07, with the labels that each got.

#3665 Oh god so much `BothScopes`...
  build.sbt
Labels: version: revision

#3672 Include lwc_local_insert config in example config
  it/testing.conf.example
Labels: version: revision

#3673 update travis cache workflow
  .travis.yml
Labels: version: revision

#3675 Delete some misc unused things
  mimir/src/main/scala/quasar/mimir/Precog.scala
  niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala
Labels: version: revision

#3678 Remove uneeded ResourceDiscovery#descendants
  api/src/main/scala/quasar/api/QueryEvaluator.scala
  api/src/main/scala/quasar/api/ResourceDiscovery.scala
  api/src/test/scala/quasar/api/ResourceDiscoverySpec.scala
  core/src/main/scala/quasar/evaluate/FederatingQueryEvaluator.scala
  core/src/test/scala/quasar/evaluate/FederatingQueryEvaluatorSpec.scala
  impl/src/main/scala/quasar/impl/datasource/ByNeedDataSource.scala
  impl/src/main/scala/quasar/impl/datasource/ConditionReportingDataSource.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalDataSource.scala
Labels: version: breaking

#3679 Move table-related files to quasar.api.table
  api/src/main/scala/quasar/api/table/PreparationResult.scala
  api/src/main/scala/quasar/api/table/PreparationSize.scala
  api/src/main/scala/quasar/api/table/PreparationStatus.scala
  api/src/main/scala/quasar/api/table/Table.scala
  api/src/main/scala/quasar/api/table/TableAttribute.scala
  api/src/main/scala/quasar/api/table/TableError.scala
  api/src/main/scala/quasar/api/table/Tables.scala
Labels: version: revision

#3680 Update argonaut to 6.2.2
  project/Dependencies.scala
Labels: version: revision

#3674 Delete TestDirective.Timeout
  it/src/test/scala/quasar/regression/QueryRegressionTest.scala
  it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala
  it/src/test/scala/quasar/regression/TestDirective.scala
Labels: version: revision

#3684 add a testjar stage to travis for PRs
  .travis.yml
Labels: version: revision

#3685 Enable MockDataSourcesSpec
  api/src/test/scala/quasar/api/MockDataSourcesSpec.scala
Labels: version: revision

#3690 various IT improvements
  it/src/main/resources/tests/joins/changedTestStatusInterim.test
  it/src/main/resources/tests/multitypeFlatten.test
  it/src/main/resources/tests/null/nullTestExprsWithMissing.test
  it/src/main/resources/tests/temporal/extract_dates.test
  it/src/main/resources/tests/typeOf.test
Labels: version: revision

#3705 Doubled compiler stack size (to help avoid intermittent SOE in patmat)
  .jvmopts
Labels: version: revision

#3706 Updated sbt-slamdata
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#3707 Upgraded to specs2 4.1.2
  project/Dependencies.scala
Labels: version: revision

#3708 Updated to sbt-slamdata 1.3.0
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#3711 Updated to sbt-slamdata 1.3.1
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#3713 Remove G[_] from Tables and update signature of allTables
  api/src/main/scala/quasar/api/table/Tables.scala
  api/src/test/scala/quasar/api/table/MockTables.scala
  api/src/test/scala/quasar/api/table/MockTablesSpec.scala
  api/src/test/scala/quasar/api/table/TablesSpec.scala
Labels: version: revision

#3714 Adjust signature of Tables#allTables
  api/src/main/scala/quasar/api/table/Tables.scala
  api/src/test/scala/quasar/api/table/MockTables.scala
  api/src/test/scala/quasar/api/table/TablesSpec.scala
Labels: version: revision

#3720 cleanup obsolete scripts
  docker/Dockerfiles/FTP/pureftpd.passwd
  docker/docker-compose.yml
  docker/scripts/assembleTestingConf
  docker/scripts/initMongodb
  docker/scripts/initPostgresql
  docker/scripts/initTestPostgresql
  docker/scripts/setupContainers
  scripts/cleanupMongo.js
  scripts/genSslTestCerts
  scripts/importTestData
  scripts/uploadTestData
Labels: version: revision

#3719 remove mongo from ITs
  it/src/main/resources/tests/concatArrayWithLiteral.test
  it/src/main/resources/tests/demo/nestedreductionsonnull.test
  it/src/main/resources/tests/demo/ordersByPricePaid.test
  it/src/main/resources/tests/demo/reductionsonnull.test
  it/src/main/resources/tests/different-flattens.test
  it/src/main/resources/tests/distinctStar.test
  it/src/main/resources/tests/fieldWithReduction.test
  it/src/main/resources/tests/flattenArrayValueAndIndexWithField.test
  it/src/main/resources/tests/flattenGroupedMap.test
  it/src/main/resources/tests/functions/coercions.test
  it/src/main/resources/tests/groupByFlatten.test
  it/src/main/resources/tests/groupBySimpleExpression.test
  it/src/main/resources/tests/havingWithMultipleProjections.test
  it/src/main/resources/tests/heterogeneousFlattenArrayIndexWithField.test
  it/src/main/resources/tests/heterogeneousFlattenArrayValueAndFlattenMapValueWithField.test
  it/src/main/resources/tests/heterogeneousFlattenArrayValueAndIndexWithField.test
  it/src/main/resources/tests/heterogeneousFlattenArrayValueWithField.test
  it/src/main/resources/tests/heterogeneousFlattenMapValueAndKeyWithField.test
  it/src/main/resources/tests/heterogeneousFlattenMapValueWithField.test
  it/src/main/resources/tests/heterogenousFlattenMapKeyWithField.test
  it/src/main/resources/tests/joins/changedTestStatus.test
  it/src/main/resources/tests/joins/simple_join.test
  it/src/main/resources/tests/mongodb/distinctStar.test
  it/src/main/resources/tests/mongodb/fakeObjectId.test
  it/src/main/resources/tests/mongodb/joinOnOid.test
  it/src/main/resources/tests/mongodb/objectIdToString.test
  it/src/main/resources/tests/mongodb/temporal/time.test
  it/src/main/resources/tests/mongodb/temporal/toFromString.test
  it/src/main/resources/tests/multilevelFlatten.test
  it/src/main/resources/tests/multistageFlatten.test
  it/src/main/resources/tests/multitypeFlatten.test
  it/src/main/resources/tests/null/nullTestExprsWithMissing.test
  it/src/main/resources/tests/range.test
  it/src/main/resources/tests/reduce/ordered_distinct_asterix.test
  it/src/main/resources/tests/resultFile/basicAnalyticQuery.test
  it/src/main/resources/tests/resultFile/constant.test
  it/src/main/resources/tests/resultFile/constantFrom.test
  it/src/main/resources/tests/selectCount.test
  it/src/main/resources/tests/servlet.test
  it/src/main/resources/tests/simpleProjectWithOneRenamed.test
  it/src/main/resources/tests/subqueryGroupBy.test
  it/src/main/resources/tests/subselectDistinctWhere.test
  it/src/main/resources/tests/subselectWhere.test
  it/src/main/resources/tests/subset/select_with_limit_and_then_offset.test
  it/src/main/resources/tests/sumDistinct.test
  it/src/main/resources/tests/sumFlattenedIntArrays.test
  it/src/main/resources/tests/temporal/time.test
  it/src/main/resources/tests/temporal/toDatetimeFunctionsInvalidData.test
  it/src/main/resources/tests/temporal/toFromString.test
  it/src/main/resources/tests/typeOf.test
  it/src/main/resources/tests/typeOfNonDateTime.test
  it/src/main/resources/tests/unifyFlattenedFieldsWithMultipleUses.test
  it/src/main/resources/tests/union/heterogeneous_union_all.test
  it/src/main/resources/tests/union/heterogeneous_union_all_filter.test
  it/src/main/resources/tests/union/multi_union_all_merge_different_types.test
  it/src/main/resources/tests/union/self_union_all.test
  it/src/main/resources/tests/union/simple_union_all.test
Labels: version: revision

#3723 Add Datasources#resourceSchema to the API
  api/src/main/scala/quasar/api/SchemaConfig.scala
  api/src/main/scala/quasar/api/datasource/DatasourceError.scala
  api/src/main/scala/quasar/api/datasource/Datasources.scala
  api/src/test/scala/quasar/api/MockSchemaConfig.scala
  api/src/test/scala/quasar/api/datasource/DatasourcesSpec.scala
  api/src/test/scala/quasar/api/datasource/MockDatasources.scala
  api/src/test/scala/quasar/api/datasource/MockDatasourcesSpec.scala
  build.sbt
  ejson/src/main/scala/quasar/ejson/EncodeEJsonK.scala
  ejson/src/main/scala/quasar/ejson/EncodeEJsonKMaterializer.scala
  impl/src/main/scala/quasar/impl/datasource/ByNeedDatasource.scala
  impl/src/main/scala/quasar/impl/datasources/DatasourceControl.scala
  impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
  impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
  impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
  impl/src/main/scala/quasar/impl/schema/SstConfig.scala
  impl/src/main/scala/quasar/impl/schema/SstSchema.scala
  impl/src/main/scala/quasar/impl/schema/package.scala
  impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
  impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala
  impl/src/test/scala/quasar/impl/datasources/MockDatasourceControl.scala
  impl/src/test/scala/quasar/impl/schema/ExtractSstSpec.scala
  it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala
  repl/src/main/scala/quasar/repl/Command.scala
  repl/src/main/scala/quasar/repl/Evaluator.scala
  repl/src/main/scala/quasar/repl/Main.scala
  repl/src/main/scala/quasar/repl/Repl.scala
  run/src/main/scala/quasar/run/Quasar.scala
  run/src/main/scala/quasar/run/ResourceRouter.scala
  run/src/main/scala/quasar/run/optics.scala
  sst/src/main/scala/quasar/sst/StructuralType.scala
Labels: version: feature

#3728 Accept the Precog instance as an argument to Quasar
  it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala
  mimir/src/main/scala/quasar/mimir/Precog.scala
  repl/src/main/scala/quasar/repl/Main.scala
  run/src/main/scala/quasar/run/Quasar.scala
Labels: version: breaking

#3731 Verify from string conversions
  it/src/main/resources/tests/functions/coercions.data
  it/src/main/resources/tests/functions/coercions.test
  it/src/main/resources/tests/functions/conversionsNonDate.data
  it/src/main/resources/tests/functions/conversionsNonDate.test
  it/src/main/resources/tests/leftshift/arrayFlattenAsInt.test
Labels: version: revision

#3694 Add toRValue benchmarks
  yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/ToRValuesBenchmark.scala
Labels: version: revision
