Repository precog/quasar, pull requests merged in 2018-10, with the labels that each got.

#3842 Newlines are my sunshine 🌻
  qscript/src/main/scala/quasar/qscript/construction.scala
Labels: version: revision

#3845 Added tectonic version bump machinery
  project/Dependencies.scala
  tectonic-version
Labels: version: revision

#3847 Add integration tests for array shifting
  it/src/main/resources/tests/deep-giraffe-array.data
  it/src/main/resources/tests/shiftDeepGiraffeArrayExcludeId.test
  it/src/main/resources/tests/shiftDeepGiraffeArrayIdOnly.test
  it/src/main/resources/tests/shiftDeepGiraffeArrayIncludeId.test
  it/src/main/resources/tests/shiftDeepGiraffeArrayIncludeIdAndField.test
Labels: version: revision

#3848 Make join test pending instead of skipped
  it/src/main/resources/tests/joins/crossJoinWithOneSidedConditions.test
Labels: version: revision

#3855 Delete quasar.common.PrimaryType
  common/src/main/scala/quasar/common/PrimaryType.scala
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
Labels: version: revision

#3860 Rename ExtraShiftedRead to InterpretedRead
  mimir/src/main/scala/quasar/mimir/evaluate/FederatedShiftedReadPlanner.scala
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
  qscript/src/main/scala/quasar/qscript/DiscoverPath.scala
  qscript/src/main/scala/quasar/qscript/InterpretedRead.scala
  qscript/src/main/scala/quasar/qscript/RenderQScriptDSL.scala
  qscript/src/main/scala/quasar/qscript/construction.scala
  qscript/src/main/scala/quasar/qscript/package.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Coalesce.scala
  qscript/src/main/scala/quasar/qscript/rewrites/ExpandDirs.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Optimize.scala
  qscript/src/main/scala/quasar/qscript/rewrites/ShiftRead.scala
  qscript/src/main/scala/quasar/qscript/rewrites/SimplifyJoin.scala
  qscript/src/test/scala/quasar/qscript/rewrites/OptimizeSpec.scala
Labels: version: breaking

#3859 Add occurence percentage to SstSchema
  impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
  impl/src/main/scala/quasar/impl/schema/Occurred.scala
  impl/src/main/scala/quasar/impl/schema/SstSchema.scala
  impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
  impl/src/test/scala/quasar/impl/schema/SstSchemaSpec.scala
  repl/src/main/scala/quasar/repl/Evaluator.scala
Labels: version: breaking

#3858 Add implicits for CPath, ParseInstruction, ParseType
  common/src/main/scala/quasar/common/CPath.scala
  frontend/src/main/scala/quasar/ParseInstruction.scala
  frontend/src/main/scala/quasar/ParseType.scala
Labels: version: revision

#3864 Delete RenderQScriptDSL
  qscript/src/main/scala/quasar/qscript/RenderQScriptDSL.scala
  qscript/src/test/scala/quasar/qscript/RenderQScriptDSLSpec.scala
Labels: version: breaking

#3865 Optimize provenance computation for Map
  qsu/src/main/scala/quasar/qsu/ApplyProvenance.scala
Labels: version: revision, ☠️

#3872 Rename shifting things into interpreter things
  mimir/src/main/scala/quasar/mimir/evaluate/FederatedShiftedReadPlanner.scala
  mimir/src/main/scala/quasar/mimir/evaluate/Interpreter.scala
  mimir/src/test/scala/quasar/mimir/evaluate/InterpreterSpec.scala
  qscript/src/main/scala/quasar/qscript/rewrites/Optimize.scala
  qscript/src/test/scala/quasar/qscript/rewrites/OptimizeSpec.scala
Labels: version: revision

#3878 Add some more Wrap tests
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
Labels: version: revision

#3879 Add some more Pivot tests
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
Labels: version: revision

#3880 Add some more Mask tests
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
Labels: version: revision

#3881 Removed flaky assertion (there's no way to do it reliably)
  impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala
Labels: version: revision

#3882 Added support for parsing precise via SlicePlate
  yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/SlicePlate.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/table/SlicePlateSpec.scala
Labels: version: feature

#3883 Add more Mask tests
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
Labels: version: revision

#3886 Remove version bump branches from travis
  .travis.yml
Labels: version: revision

#3888 Allow edits of prepared and preparing tables
  api/src/test/scala/quasar/api/table/MockTables.scala
  api/src/test/scala/quasar/api/table/TablesSpec.scala
  impl/src/main/scala/quasar/impl/table/DefaultTables.scala
Labels: version: feature, ☠️

#3889 Add sql parser specs for a couple addition cases that used to not work
  sql/src/test/scala/quasar/sql/SqlParserSpec.scala
Labels: version: revision

#3895 Implement InterpretedRead rewrites through static array derefs
  it/src/main/resources/tests/deep-giraffe-array2.data
  it/src/main/resources/tests/shiftDeepGiraffeArrayDeref.test
  it/src/main/resources/tests/shiftDeepGiraffeArrayDeref2.test
  qscript/src/main/scala/quasar/qscript/rewrites/Optimize.scala
  qscript/src/test/scala/quasar/qscript/rewrites/OptimizeSpec.scala
Labels: version: feature

#3900 Fixed issue with emiting FinishRow on a singleton vector pivot
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/PivotPlate.scala
Labels: version: revision

#3907 compact/canonicalize in execute (after evaluation)
  mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
  mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala
Labels: version: revision

#3910 Added file case to ExternalConfig
  impl/src/main/scala/quasar/impl/external/ExternalConfig.scala
  impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
Labels: version: feature

#3914 Use already-materialized column when materializing
  mimir/src/test/scala/quasar/mimir/storage/MimirPTableStoreSpec.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Column.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Labels: version: revision
