Repository precog/quasar, pull requests merged in 2018-08, with the labels that each got.

#3735 Publish tests for all projects
  build.sbt
Labels: version: revision

#3739 add NoOp command in repl
  repl/src/main/scala/quasar/repl/Command.scala
  repl/src/main/scala/quasar/repl/Evaluator.scala
Labels: version: revision

#3741 Corrected future-derived IO continuations remaining on wrong pool
  foundation/src/main/scala/quasar/contrib/cats/effect/package.scala
  it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala
  mimir/src/main/scala/quasar/mimir/Precog.scala
  mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/NIHDBProjection.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/VFSColumnarTableModule.scala
Labels: version: revision

#3740 Log plugin version when loading
  impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
  impl/src/main/scala/quasar/impl/external/Plugin.scala
Labels: version: revision

#3743 Fixed post-projection of sparsenByMod index when mod > 64
  blueeyes/src/main/java/quasar/precog/BitSet.java
  blueeyes/src/test/scala/quasar/precog/BitSetSpec.scala
  it/src/main/resources/tests/veryHeterogeneousFlattenArrayIndexWithField.test
Labels: version: revision

#3744 Enable preserving top K keys during SST compression
  impl/src/main/scala/quasar/impl/schema/SstConfig.scala
  impl/src/main/scala/quasar/impl/schema/package.scala
  impl/src/test/scala/quasar/impl/schema/ExtractSstSpec.scala
  sst/src/main/scala/quasar/sst/compression.scala
  sst/src/test/scala/quasar/sst/CompressionSpec.scala
Labels: version: breaking

#3746 add IT for shifting wildcard map key with shift map value
  it/src/main/resources/tests/nestedMapWildcardShiftWithShiftMap.test
  it/src/main/resources/tests/nested_map.data
Labels: version: revision

#3745 Only warn when loading fails for all datasource kinds
  impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
  repl/src/main/resources/log4j.properties
Labels: version: revision

#3748 Delete quasar's binary data type
  blueeyes/src/main/scala/quasar/blueeyes/json/JValue.scala
  blueeyes/src/main/scala/quasar/precog/common/CValue.scala
  common/src/main/scala/quasar/common/PrimaryType.scala
  common/src/main/scala/quasar/common/data/Data.scala
  common/src/main/scala/quasar/common/data/QDataData.scala
  common/src/test/scala/quasar/common/data/DataGenerators.scala
  common/src/test/scala/quasar/common/data/QDataDataSpec.scala
  datagen/src/main/scala/quasar/datagen/dist.scala
  datagen/src/test/scala/quasar/datagen/GenerateSpec.scala
  ejson/src/main/scala/quasar/ejson/DecodeEJson.scala
  ejson/src/main/scala/quasar/ejson/EJson.scala
  ejson/src/main/scala/quasar/ejson/EncodeEJson.scala
  ejson/src/main/scala/quasar/ejson/Extension.scala
  ejson/src/main/scala/quasar/ejson/Fixed.scala
  ejson/src/main/scala/quasar/ejson/JsonCodec.scala
  ejson/src/main/scala/quasar/ejson/TypeTag.scala
  ejson/src/main/scala/quasar/ejson/Z85.scala
  ejson/src/main/scala/quasar/ejson/optics.scala
  ejson/src/test/scala/quasar/ejson/EJsonArbitrary.scala
  ejson/src/test/scala/quasar/ejson/Z85.scala
  frontend/src/main/scala/quasar/Type.scala
  frontend/src/main/scala/quasar/frontend/data/DataCodec.scala
  frontend/src/main/scala/quasar/tpe/package.scala
  frontend/src/test/scala/quasar/TypeGenerators.scala
  frontend/src/test/scala/quasar/frontend/data/DataCodecSpec.scala
  frontend/src/test/scala/quasar/types.scala
  impl/src/main/scala/quasar/impl/schema/package.scala
  impl/src/test/scala/quasar/impl/schema/ExtractSstSpec.scala
  qscript/src/main/scala/quasar/qscript/RenderQScriptDSL.scala
  qscript/src/test/scala/quasar/qscript/RenderQScriptDSLSpec.scala
  qsu/src/main/scala/quasar/qsu/QScriptUniform.scala
  repl/src/test/scala/quasar/repl/PrettifySpec.scala
  sst/src/main/scala/quasar/sst/TypeStat.scala
  sst/src/main/scala/quasar/sst/compression.scala
  sst/src/main/scala/quasar/sst/package.scala
  sst/src/test/scala/quasar/sst/CompressionSpec.scala
  sst/src/test/scala/quasar/sst/TypeStatArbitrary.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/bytecode/JType.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala
Labels: version: breaking

#3751 update encrypted aws id
  scripts/aws-access-key-id.bin
  scripts/aws-secret-access-key.bin
Labels: version: revision

#3755 Use Sync to delay effect in MockTablesSpec
  api/src/test/scala/quasar/api/table/MockTablesSpec.scala
Labels: version: revision

#3759 Remove unused blueeyes imports
  blueeyes/src/main/scala/quasar/precog/common/ColumnRef.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/CPathTraversal.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/ArbitrarySValue.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/CogroupSpec.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/TestIdentities.scala
Labels: version: revision

#3760 Implement tri-numeric support in renderCsv
  yggdrasil/src/main/scala/quasar/yggdrasil/NoCsvEscape.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
  yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala
Labels: version: feature

#3761 Move NullRemover into quasar.yggdrasil.util
  repl/src/main/scala/quasar/repl/Evaluator.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/util/NullRemover.scala
Labels: version: revision

#3764 in repl also handle errors that are raised in stream
  repl/src/main/scala/quasar/repl/Evaluator.scala
Labels: version: revision

#3771 mark tests with ignoreFieldOrder
  it/src/main/resources/tests/backendStatuses.test
  it/src/main/resources/tests/bigdecimal.test
  it/src/main/resources/tests/boulderLikePop.test
  it/src/main/resources/tests/concatBetween.test
  it/src/main/resources/tests/constantAndGrouped.test
  it/src/main/resources/tests/convertFromString.test
  it/src/main/resources/tests/countAndSumGroupedBySingleField.test
  it/src/main/resources/tests/demo/groupedSelectOfNestedReduction.test
  it/src/main/resources/tests/derivedFunctionCeil.test
  it/src/main/resources/tests/derivedFunctionFloor.test
  it/src/main/resources/tests/derivedFunctionRound.test
  it/src/main/resources/tests/derivedFunctionTrunc.test
  it/src/main/resources/tests/fieldOrder.test
  it/src/main/resources/tests/fieldWithReduction.test
  it/src/main/resources/tests/flattenArrayLeftWithUnflattened.test
  it/src/main/resources/tests/flattenArrayWithUnflattened.test
  it/src/main/resources/tests/functions/simple_if_undefined.test
  it/src/main/resources/tests/groupByExpression.test
  it/src/main/resources/tests/groupBySimpleExpression.test
  it/src/main/resources/tests/joins/groupedJoin.test
  it/src/main/resources/tests/joins/joinDistinct.test
  it/src/main/resources/tests/joins/joinSubSelects.test
  it/src/main/resources/tests/joins/joinWithComplexCondition.test
  it/src/main/resources/tests/joins/joinWithMultipleConditions.test
  it/src/main/resources/tests/joins/joinWithReversedCondition.test
  it/src/main/resources/tests/joins/selfjoinWithComplexCondition.test
  it/src/main/resources/tests/jsWithNonJsFilter.test
  it/src/main/resources/tests/letBinding.test
  it/src/main/resources/tests/longCitiesWithLength.test
  it/src/main/resources/tests/negatedRegex.test
  it/src/main/resources/tests/null/toFromString.test
  it/src/main/resources/tests/numericFieldNames.test
  it/src/main/resources/tests/projectIndexFromGroup.test
  it/src/main/resources/tests/projectIndexFromGroupWithFilter.test
  it/src/main/resources/tests/regression/bug2226.test
  it/src/main/resources/tests/selectArrayElement.test
  it/src/main/resources/tests/selectCount.test
  it/src/main/resources/tests/simpleProjectWithOneRenamed.test
  it/src/main/resources/tests/sortByJS.test
  it/src/main/resources/tests/sumDistinct.test
  it/src/main/resources/tests/trivialGroup.test
  it/src/main/resources/tests/unifyFlattenedFieldsWithUnflattened.test
  it/src/main/resources/tests/union/self_union.test
  it/src/main/resources/tests/union/self_union_all.test
  it/src/main/resources/tests/union/simple_union.test
  it/src/main/resources/tests/union/simple_union_all.test
  it/src/main/resources/tests/usefulGroupBy.test
  it/src/main/resources/tests/zipsByCityLength.test
Labels: version: revision

#3772 Use ShiftType in mimir's evaluation of LeftShift
  it/src/main/resources/tests/veryHeterogeneousShiftArrayValueWithFieldOnMap.test
  mimir/src/main/scala/quasar/mimir/QScriptCorePlanner.scala
Labels: version: revision

#3774 make ArrayColumn.update return this.type instead of Unit
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Column.scala
  yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Labels: version: revision
