Repository precog/quasar, pull requests merged in 2019-10, with the labels that each got.

#4379 add numeric conversions
  foundation/src/main/scala/quasar/numeric/NumericConversions.scala
Labels: version: feature

#4381 Purge everything related to table preparation
  api/src/main/scala/quasar/api/table/PreparationEvent.scala
  api/src/main/scala/quasar/api/table/PreparationResult.scala
  api/src/main/scala/quasar/api/table/PreparationStatus.scala
  api/src/main/scala/quasar/api/table/TableError.scala
  api/src/main/scala/quasar/api/table/Tables.scala
  api/src/test/scala/quasar/api/table/MockTables.scala
  api/src/test/scala/quasar/api/table/MockTablesSpec.scala
  api/src/test/scala/quasar/api/table/TablesSpec.scala
  impl/src/main/scala/quasar/impl/table/DefaultTables.scala
  impl/src/main/scala/quasar/impl/table/PreparationsManager.scala
  impl/src/test/scala/quasar/impl/table/DefaultTablesSpec.scala
  impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala
  run/src/main/scala/quasar/run/Quasar.scala
Labels: version: breaking

#4383 handle QueryResult.Stateful in ssts
  impl/src/main/scala/quasar/impl/parsing/ResultParser.scala
  impl/src/test/scala/quasar/impl/datasource/CountBoolPlate.scala
  impl/src/test/scala/quasar/impl/datasources/CompositeResourceSchemaSpec.scala
  impl/src/test/scala/quasar/impl/datasources/SimpleCompositeResourceSchemaSpec.scala
Labels: version: feature

#4386 Implement a LocalStatefulDatasource
  impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulDatasource.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulDatasourceModule.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulPlate.scala
  impl/src/main/scala/quasar/impl/datasource/local/package.scala
  impl/src/test/scala/quasar/impl/datasource/local/LocalDatasourceSpec.scala
Labels: version: feature

#4389 create the stateful plate within the effect in the local ds
  impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulDatasource.scala
  impl/src/main/scala/quasar/impl/parsing/ResultParser.scala
  impl/src/test/scala/quasar/impl/datasources/CompositeResourceSchemaSpec.scala
  impl/src/test/scala/quasar/impl/datasources/SimpleCompositeResourceSchemaSpec.scala
Labels: version: breaking

#4390 bump quasar-datasource-postgres
  scripts/quasarPublishAndTag
Labels: version: revision

#4323 Update shims to 2.0.0
  build.sbt
Labels: :stop_sign:

#4325 Update cats-effect to 2.0.0
  project/Versions.scala
Labels: :stop_sign:

#4388 Update algebra, algebra-laws to 2.0.0
  project/Versions.scala
Labels: version: revision

#4402 Use default settings for ProxySearch
  foundation/src/main/scala/quasar/contrib/proxy/Search.scala
Labels: version: revision

#4399 Update shims to 2.1.0
  build.sbt
Labels: version: revision

#4400 Update woodstox-core to 6.0.2
  build.sbt
Labels: version: revision

#4403 Update sbt to 1.3.3
  project/build.properties
Labels: version: revision

#4424 Make all shims imports explicit
  api/src/main/scala/quasar/api/datasource/DatasourceError.scala
  api/src/test/scala/quasar/api/datasource/DatasourcesSpec.scala
  api/src/test/scala/quasar/api/datasource/MockDatasourcesSpec.scala
  api/src/test/scala/quasar/api/table/MockTablesSpec.scala
  connector/src/main/scala/quasar/connector/QueryResult.scala
  connector/src/test/scala/quasar/connector/DatasourceSpec.scala
  connector/src/test/scala/quasar/connector/datasource/MapBasedDatasourceSpec.scala
  foundation/src/main/scala/quasar/contrib/fs2/convert.scala
  impl/src/main/scala/quasar/impl/datasource/AggregatingDatasource.scala
  impl/src/main/scala/quasar/impl/datasource/local/EvaluableLocalDatasource.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalConfig.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalDestination.scala
  impl/src/main/scala/quasar/impl/datasources/DefaultDatasourceManager.scala
  impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
  impl/src/main/scala/quasar/impl/datasources/middleware/AggregatingMiddleware.scala
  impl/src/main/scala/quasar/impl/destinations/DefaultDestinationManager.scala
  impl/src/main/scala/quasar/impl/destinations/DefaultDestinations.scala
  impl/src/main/scala/quasar/impl/evaluate/RValueScalarStagesInterpreter.scala
  impl/src/main/scala/quasar/impl/external/ExternalConfig.scala
  impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
  impl/src/main/scala/quasar/impl/schema/SstSchema.scala
  impl/src/main/scala/quasar/impl/storage/ConcurrentMapIndexedStore.scala
  impl/src/main/scala/quasar/impl/table/DefaultTables.scala
  impl/src/test/scala/quasar/impl/datasource/AggregatingDatasourceSpec.scala
  impl/src/test/scala/quasar/impl/datasource/local/LocalConfigSpec.scala
  impl/src/test/scala/quasar/impl/datasource/local/LocalDatasourceSpec.scala
  impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala
  impl/src/test/scala/quasar/impl/datasources/middleware/ConditionReportingMiddlewareSpec.scala
  impl/src/test/scala/quasar/impl/destinations/DefaultDestinationManagerSpec.scala
  impl/src/test/scala/quasar/impl/destinations/DefaultDestinationsSpec.scala
  impl/src/test/scala/quasar/impl/destinations/MockDestination.scala
  impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
  impl/src/test/scala/quasar/impl/schema/SstSchemaSpec.scala
  impl/src/test/scala/quasar/impl/storage/AntiEntropyStoreSpec.scala
  impl/src/test/scala/quasar/impl/storage/ConcurrentMapIndexedStoreSpec.scala
  impl/src/test/scala/quasar/impl/storage/PureIndexedStoreSpec.scala
  impl/src/test/scala/quasar/impl/storage/RefIndexedStoreSpec.scala
  impl/src/test/scala/quasar/impl/storage/TimestampedStoreSpec.scala
  impl/src/test/scala/quasar/impl/table/DefaultTablesSpec.scala
  qsu/src/main/scala/quasar/qsu/Bucketing.scala
  qsu/src/main/scala/quasar/qsu/MinimizeAutoJoins.scala
  qsu/src/main/scala/quasar/qsu/mra/AutoJoin.scala
  qsu/src/main/scala/quasar/qsu/mra/Identities.scala
  qsu/src/main/scala/quasar/qsu/mra/ProvImpl.scala
  qsu/src/main/scala/quasar/qsu/mra/package.scala
  qsu/src/test/scala/quasar/qsu/mra/IdentitiesSpec.scala
  run/src/main/scala/quasar/run/Quasar.scala
  run/src/main/scala/quasar/run/QuasarError.scala
  run/src/main/scala/quasar/run/Sql2QueryEvaluator.scala
  run/src/main/scala/quasar/run/store/Store.scala
  run/src/test/scala/quasar/CountingQScriptEvaluator.scala
  run/src/test/scala/quasar/CountingRegressionSpec.scala
  run/src/test/scala/quasar/QScriptRegressionSpec.scala
  run/src/test/scala/quasar/RegressionQScriptEvaluator.scala
Labels: version: revision

#4426 add scalar stage spec for undefineds on both sides
  frontend/src/test/scala/quasar/ScalarStageSpec.scala
Labels: version: revision
