Repository precog/quasar, pull requests merged in 2019-09, with the labels that each got.

#4322 More robust naming and reindexing in simplifyJoin
  qsu/src/main/scala/quasar/qsu/minimizers/MergeCartoix.scala
  qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Labels: version: revision

#4314 Update sbt-slamdata to 3.2.1
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#4317 Update woodstox-core to 6.0.0
  build.sbt
Labels: version: revision

#4332 Added autobump for thoughtspot destination
  scripts/quasarPublishAndTag
Labels: version: revision

#4331 Update sbt-coursier to 2.0.0-RC3-4
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#4336 Add row limiting to ResultRender
  api/src/main/scala/quasar/api/push/ResultRender.scala
  impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
  impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
Labels: version: breaking

#4345 Make CSV header rendering optional for destinations
  api/src/main/scala/quasar/api/destination/ResultSink.scala
  api/src/main/scala/quasar/api/push/ResultRender.scala
  impl/src/main/scala/quasar/impl/datasource/local/LocalDestination.scala
  impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
  impl/src/test/scala/quasar/impl/destinations/MockDestination.scala
  impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
Labels: version: breaking

#4347 Updated sbt-slamdata to 4.0.1
  .travis.yml
  build.sbt
  project/build.properties
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#4356 Use ISO_OFFSET_DATE_TIME to format OffsetDateTime in csv
  api/src/main/scala/quasar/api/push/RenderConfig.scala
Labels: version: revision

#4359 Added null sentinel to the render config
  api/src/main/scala/quasar/api/push/RenderConfig.scala
Labels: version: feature

#4360 Add tests for undefined cases of ToLocal and ToOffset
  frontend/src/test/scala/quasar/std/StdLibSpec.scala
Labels: version: revision

#4358 Added autobump for postgres destination
  scripts/quasarPublishAndTag
Labels: version: revision

#4367 Burn the tabs with fire
  sst/src/main/scala/quasar/sst/TypeStat.scala
Labels: version: revision

#4341 Update woodstox-core to 6.0.1
  build.sbt
Labels: version: revision

#4342 Update refined, refined-scalacheck, ... to 0.9.10
  project/Versions.scala
Labels: version: revision

#4343 Update specs2-core, specs2-scalacheck, ... to 4.7.1
  project/Versions.scala
Labels: version: revision

#4361 Update sbt to 1.3.2
  project/build.properties
Labels: version: revision

#4365 Update netty-all to 4.1.42.Final
  project/Versions.scala
Labels: version: revision

#4369 Avoid leaking threads when futures error
  foundation/src/main/scala/quasar/contrib/cats/effect/package.scala
Labels: version: revision

#4377 Added autobump for s3 destination
  scripts/quasarPublishAndTag
Labels: version: revision

#4370 added updates stream test
  impl/src/test/scala/quasar/impl/storage/TimestampedStoreSpec.scala
Labels: version: revision
