Repository precog/quasar, pull requests merged in 2019-02, with the labels that each got.

#4074 log query and base path
  run/src/main/scala/quasar/run/Sql2QueryEvaluator.scala
Labels: version: revision

#4075 Remove join-condition related side effects
  qsu/src/main/scala/quasar/qsu/ExpandShifts.scala
Labels: version: revision

#4078 Ensure unique names when replacing a table
  api/src/main/scala/quasar/api/table/TableError.scala
  api/src/main/scala/quasar/api/table/Tables.scala
  api/src/test/scala/quasar/api/table/MockTables.scala
  api/src/test/scala/quasar/api/table/TablesSpec.scala
  impl/src/main/scala/quasar/impl/table/DefaultTables.scala
Labels: version: breaking

#4080 Made PhaseResults lazy (using Eval) to tree logging costs in production
  common/src/main/scala/quasar/common/package.scala
  qsu/src/main/scala/quasar/qsu/LPtoQS.scala
Labels: version: breaking

#4086 Add the rest of the temporal scalars to ColumnType
  api/src/main/scala/quasar/api/table/ColumnType.scala
  frontend/src/main/scala/quasar/ScalarStage.scala
  impl/src/main/scala/quasar/impl/evaluate/RValueScalarStagesInterpreter.scala
Labels: version: feature

#4085 Delete Tables#liveData
  api/src/main/scala/quasar/api/table/Tables.scala
  api/src/test/scala/quasar/api/table/MockTables.scala
  api/src/test/scala/quasar/api/table/TablesSpec.scala
  impl/src/main/scala/quasar/impl/table/DefaultTables.scala
Labels: version: breaking

#4088 Don't compress SST in map-size chunks
  impl/src/main/scala/quasar/impl/schema/ProgressiveSst.scala
Labels: version: revision

#4087 Delete incorrect Eq MapFuncCore normalization case
  qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
Labels: version: revision

#4090 Default provenance for MapFunc should be conjunction of inputs
  qscript/src/test/scala/quasar/qscript/provenance/DimensionSpec.scala
  qscript/src/test/scala/quasar/qscript/provenance/ProvSpec.scala
  qsu/src/main/scala/quasar/qsu/ApplyProvenance.scala
  qsu/src/test/scala/quasar/qsu/ApplyProvenanceSpec.scala
  qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Labels: version: revision
