Repository precog/quasar, pull requests merged in 2019-01, with the labels that each got.

#4030 Change pivot parse instruction from multi to single
  frontend/src/main/scala/quasar/ParseInstruction.scala
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
  impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
  impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala
  qscript/src/main/scala/quasar/qscript/rewrites/RewritePushdown.scala
  qscript/src/test/scala/quasar/qscript/rewrites/RewritePushdownSpec.scala
Labels: version: breaking

#4035 Updated sbt-slamdata
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#4033 Shift coalescence associativity.
  qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala
  qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Labels: version: revision

#4039 Add impl of RValue Cartesian interpretation and tests
  common/src/main/scala/quasar/common/CPath.scala
  frontend/src/main/scala/quasar/ParseInstruction.scala
  frontend/src/test/scala/quasar/JsonSpec.scala
  frontend/src/test/scala/quasar/ParseInstructionSpec.scala
  impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
  impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala
Labels: version: breaking

#4040 Moved dependencies into build.sbt
  build.sbt
  project/Dependencies.scala
  project/Versions.scala
Labels: version: revision

#4042 Updated plugin
  project/plugins.sbt
  project/project/plugins.sbt
Labels: version: revision

#4043 Add a MonadError_ instance for cats.data.WriterT
  foundation/src/main/scala/quasar/contrib/cats/writerT.scala
Labels: version: feature

#4045 Add unit test for provenance computation bug ch2068
  qsu/src/test/scala/quasar/qsu/ApplyProvenanceSpec.scala
Labels: version: revision

#4046 Add qscript regression tests for provenance bug ch2068
  run/src/test/scala/quasar/QScriptRegressionSpec.scala
Labels: version: revision

#4048 Updated to shims 1.7
  build.sbt
Labels: version: revision

#4047 Add test cases for multi line searching to StdLibSpec
  frontend/src/test/scala/quasar/std/StdLibSpec.scala
Labels: version: breaking

#4053 Added thoth autobump
  scripts/quasarPublishAndTag
Labels: version: revision

#4066 Take the entire provenance chain into account
  qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala
  qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Labels: :skull_and_crossbones:, version: revision

#4068 parallel RValue Cartesian interpreter
  impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
  impl/src/test/scala/quasar/impl/evaluate/RValueCartesianSpec.scala
  impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala
Labels: version: breaking
